name: Expo React Native Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  expo-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        sentry-version: [^6.11.0]
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build main package
        run: yarn workspace sentry-testkit build

      - name: Install Sentry React Native package
        working-directory: ./apps/expo-react-native-test-app
        run: yarn add @sentry/react-native@"${{ matrix.sentry-version }}"

      - name: Run Expo app tests
        run: yarn workspace expo-react-native-test-app test
